[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
testnet = "${HEDERA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# DEPLOY COMMAND
# forge script script/HederaToken.s.sol:HederaTokenScript --rpc-url testnet --broadcast --slow